const SPREADSHEET_ID = '15KswxkGVrBV4ApyCQEzo6DzjKW6uR0B5fVEipBA9zpg';
const enc = new TextEncoder();
const b64url = input => btoa(typeof input === 'string' ? input : String.fromCharCode(...new Uint8Array(input))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
const colLetter = n => { let s=''; while(n){s=String.fromCharCode(64+(n-1)%26)+s;n=Math.floor((n-1)/26)} return s };
function cors(request, env){const origin=request.headers.get('Origin')||'';return {'Access-Control-Allow-Origin':env.ALLOWED_ORIGIN===origin?origin:env.ALLOWED_ORIGIN||'*','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Vary':'Origin'}}
function json(value,request,env,status=200){return new Response(JSON.stringify(value),{status,headers:{...cors(request,env),'Content-Type':'application/json;charset=utf-8'}})}
async function googleToken(env){const a=JSON.parse(env.GOOGLE_SERVICE_ACCOUNT_JSON);const now=Math.floor(Date.now()/1000), header=b64url(JSON.stringify({alg:'RS256',typ:'JWT'})), claims=b64url(JSON.stringify({iss:a.client_email,scope:'https://www.googleapis.com/auth/spreadsheets',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3500}));const key=await crypto.subtle.importKey('pkcs8',Uint8Array.from(atob(a.private_key.replace(/-----(BEGIN|END) PRIVATE KEY-----|\s/g,'')),x=>x.charCodeAt(0)),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,enc.encode(header+'.'+claims));const body=new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:header+'.'+claims+'.'+b64url(sig)});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!r.ok)throw new Error('Google authentication failed');return (await r.json()).access_token}
async function sheets(env,path,init={}){const token=await googleToken(env);const r=await fetch('https://sheets.googleapis.com/v4/spreadsheets/'+SPREADSHEET_ID+path,{...init,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',...(init.headers||{})}});if(!r.ok)throw new Error(`Google Sheets error (${r.status})`);return r.status===204?null:r.json()}
const bordered=v=>{const b=v?.userEnteredFormat?.borders;return b&&Object.values(b).some(x=>x?.style&&x.style!=='NONE')};
function makeSide(sheet, side){const tableCol=side==='male'?0:7, rows=sheet.data?.[0]?.rowData||[];return rows.map((row,rowIndex)=>{const table=row.values?.[tableCol]?.formattedValue;if(!table||rowIndex===0)return null;let cells=(row.values||[]).map((v,col)=>({v,col})).filter(x=>x.col!==tableCol&&bordered(x.v));cells.sort((a,b)=>side==='male'?a.col-b.col:b.col-a.col);return {table:String(table),seats:cells.map((x,i)=>({side,row:rowIndex+1,col:x.col+1,table:String(table),position:i+1,name:x.v.formattedValue||'',className:x.v.note||''}))}}).filter(Boolean)}
async function plan(env){const fields='sheets(properties(title),data(rowData(values(formattedValue,note,userEnteredFormat/borders))))';const raw=await sheets(env,`?includeGridData=true&fields=${encodeURIComponent(fields)}`);const find=n=>raw.sheets.find(s=>s.properties.title===n);const ds=await sheets(env,'/values/DS!A2:B');return {female:makeSide(find('nữ'),'female'),male:makeSide(find('Nam'),'male'),students:(ds.values||[]).filter(x=>x[1]).map(x=>({className:x[0]||'',name:x[1]}))}}
function sheetOf(side){return side==='female'?'nữ':'Nam'}
async function updateSeat(env,b){if(!['male','female'].includes(b.side)||!Number.isInteger(b.row)||!Number.isInteger(b.col))throw new Error('Vị trí không hợp lệ');const cell=`${sheetOf(b.side)}!${colLetter(b.col)}${b.row}`;await sheets(env,`/values/${encodeURIComponent(cell)}?valueInputOption=RAW`,{method:'PUT',body:JSON.stringify({values:[[b.name||'']]})});await sheets(env,`:batchUpdate`,{method:'POST',body:JSON.stringify({requests:[{updateCells:{range:{sheetId:(await sheetId(env,sheetOf(b.side))),startRowIndex:b.row-1,endRowIndex:b.row,startColumnIndex:b.col-1,endColumnIndex:b.col},rows:[{values:[{note:b.className||''}]}],fields:'note'}}]})})}
async function sheetId(env,title){const r=await sheets(env,'?fields=sheets(properties(sheetId,title))');const s=r.sheets.find(x=>x.properties.title===title);if(!s)throw new Error('Không tìm thấy sheet '+title);return s.properties.sheetId}
async function addSeat(env,b){if(!['male','female'].includes(b.side))throw new Error('Bên ngồi không hợp lệ');const p=await plan(env), tables=p[b.side],t=tables.find(x=>String(x.table)===String(b.table));if(!t?.seats.length)throw new Error('Không tìm thấy bàn hoặc chỗ ngồi');const last=t.seats[t.seats.length-1], newCol=last.col+(b.side==='male'?1:-1);if(newCol<1)throw new Error('Không thể thêm chỗ ở ngoài sheet');const id=await sheetId(env,sheetOf(b.side));const border={style:'SOLID',color:{red:0.45,green:0.5,blue:0.55}};await sheets(env,':batchUpdate',{method:'POST',body:JSON.stringify({requests:[{updateCells:{range:{sheetId:id,startRowIndex:last.row-1,endRowIndex:last.row,startColumnIndex:newCol-1,endColumnIndex:newCol},rows:[{values:[{userEnteredFormat:{borders:{top:border,bottom:border,left:border,right:border}}}]}],fields:'userEnteredFormat.borders'}}]})})}
export default {async fetch(request,env){if(request.method==='OPTIONS')return new Response(null,{headers:cors(request,env)});try{const u=new URL(request.url);if(u.pathname==='/api/plan'&&request.method==='GET')return json(await plan(env),request,env);if(u.pathname==='/api/seat'&&request.method==='POST'){await updateSeat(env,await request.json());return json({ok:true},request,env)}if(u.pathname==='/api/seat/add'&&request.method==='POST'){await addSeat(env,await request.json());return json({ok:true},request,env)}return json({error:'Not found'},request,env,404)}catch(e){return json({error:e.message||'Server error'},request,env,500)}}};
