const SPREADSHEET_ID='15KswxkGVrBV4ApyCQEzo6DzjKW6uR0B5fVEipBA9zpg';
const enc=new TextEncoder();
const b64url=input=>btoa(typeof input==='string'?input:String.fromCharCode(...new Uint8Array(input))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
const SEAT_COUNTS=[2,2,3,3,4,4,4,4,5,5,6,7,7,7,7,7,7,7],MAX_SEATS=9;
const parseTable=value=>{const match=/^(\d+)\.([AB])$/.exec(String(value||''));if(!match)return null;const number=Number(match[1]);return number>=1&&number<=SEAT_COUNTS.length?{number,lane:match[2],id:`${number}.${match[2]}`} : null};

function cors(request,env){const origin=request.headers.get('Origin')||'';return {'Access-Control-Allow-Origin':env.ALLOWED_ORIGIN===origin?origin:env.ALLOWED_ORIGIN||'*','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Vary':'Origin'}}
function json(value,request,env,status=200){return new Response(JSON.stringify(value),{status,headers:{...cors(request,env),'Content-Type':'application/json;charset=utf-8'}})}
function sheetOf(side){return side==='female'?'Nữ':'Nam'}
function parseStudent(value){const text=String(value||''),split=text.lastIndexOf(' - ');return split<0?{value:text,name:text,className:''}:{value:text,name:text.slice(0,split),className:text.slice(split+3)}}

async function googleToken(env){const a=JSON.parse(env.GOOGLE_SERVICE_ACCOUNT_JSON),now=Math.floor(Date.now()/1000),header=b64url(JSON.stringify({alg:'RS256',typ:'JWT'})),claims=b64url(JSON.stringify({iss:a.client_email,scope:'https://www.googleapis.com/auth/spreadsheets',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3500}));const key=await crypto.subtle.importKey('pkcs8',Uint8Array.from(atob(a.private_key.replace(/-----(BEGIN|END) PRIVATE KEY-----|\s/g,'')),x=>x.charCodeAt(0)),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,enc.encode(header+'.'+claims));const body=new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:header+'.'+claims+'.'+b64url(sig)});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!r.ok)throw new Error('Google authentication failed');return (await r.json()).access_token}
async function sheets(env,path,init={}){const token=await googleToken(env),r=await fetch('https://sheets.googleapis.com/v4/spreadsheets/'+SPREADSHEET_ID+path,{...init,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',...(init.headers||{})}});if(!r.ok)throw new Error(`Google Sheets error (${r.status})`);return r.status===204?null:r.json()}

// Sheet "Nam" và "Nữ" là kho dữ liệu, không phải sơ đồ ô.
// Mỗi dòng: cột A = Bàn, cột B = Vị trí, cột C = "Tên - Lớp".
async function ensureHeaders(env,side){const sheet=sheetOf(side),range=encodeURIComponent(`${sheet}!A1:C1`),current=await sheets(env,`/values/${range}`),head=current.values?.[0]||[];if(head[0]==='Bàn'&&head[1]==='Vị trí'&&head[2]==='Tên - Lớp')return;await sheets(env,`/values/${range}?valueInputOption=RAW`,{method:'PUT',body:JSON.stringify({values:[['Bàn','Vị trí','Tên - Lớp']]})})}
async function seatRows(env,side){const sheet=sheetOf(side),result=await sheets(env,`/values/${encodeURIComponent(`${sheet}!A2:C`)}`);return (result.values||[]).map((values,index)=>{const rawTable=String(values[0]||''),legacy=Number(rawTable),table=parseTable(rawTable)?.id||(Number.isInteger(legacy)&&legacy>=1&&legacy<=SEAT_COUNTS.length?`${legacy}.A`:'');return {sheetRow:index+2,rawTable,table,position:Number(values[1]),value:String(values[2]||'')}}).filter(x=>parseTable(x.table)&&Number.isInteger(x.position)&&x.position>=1&&x.position<=MAX_SEATS)}
function makeSide(records,side){const lanes=side==='male'?['A','B']:['B','A'];return SEAT_COUNTS.flatMap((base,index)=>lanes.map(lane=>{const number=index+1,row=`${number}.${lane}`,own=records.filter(x=>x.table===row),count=Math.max(base,...own.map(x=>x.position));return {table:row,seats:Array.from({length:count},(_,i)=>{const position=i+1,saved=own.find(x=>x.position===position),value=saved?.value||'';return {side,row,col:position,table:row,position,...parseStudent(value)}})} }))}
async function plan(env){const [femaleRows,maleRows,ds]=await Promise.all([seatRows(env,'female'),seatRows(env,'male'),sheets(env,'/values/DS!A2:B')]);return {female:makeSide(femaleRows,'female'),male:makeSide(maleRows,'male'),students:(ds.values||[]).filter(x=>x[1]).map(x=>({className:x[0]||'',name:x[1]}))}}

function validSeat(b){return ['male','female'].includes(b.side)&&!!parseTable(b.row)&&Number.isInteger(b.position)&&b.position>=1&&b.position<=MAX_SEATS}
async function updateSeat(env,b){if(!validSeat(b))throw new Error('Vị trí không hợp lệ');await ensureHeaders(env,b.side);const table=String(b.row),sheet=sheetOf(b.side),value=b.name?`${b.name} - ${b.className||''}`.trim().replace(/ -$/,''):'';const records=await seatRows(env,b.side),found=records.find(x=>x.table===table&&x.position===b.position);if(found){const range=`${sheet}!A${found.sheetRow}:C${found.sheetRow}`;await sheets(env,`/values/${encodeURIComponent(range)}?valueInputOption=RAW`,{method:'PUT',body:JSON.stringify({values:[[table,b.position,value]]})});}else if(value){await sheets(env,`/values/${encodeURIComponent(`${sheet}!A:C`)}:append?valueInputOption=RAW&insertDataOption=INSERT_ROWS`,{method:'POST',body:JSON.stringify({values:[[table,b.position,value]]})})}return `${sheet}: bàn ${table}, vị trí ${b.position}`}
async function addSeat(env,b){const table=parseTable(b.table);if(!['male','female'].includes(b.side)||!table||table.number<7)throw new Error('Chỉ có thể thêm chỗ từ bàn 7 đến 18');await ensureHeaders(env,b.side);const records=await seatRows(env,b.side),count=Math.max(SEAT_COUNTS[table.number-1],...records.filter(x=>x.table===table.id).map(x=>x.position));if(count>=MAX_SEATS)throw new Error(`Bàn này đã đủ tối đa ${MAX_SEATS} vị trí`);const sheet=sheetOf(b.side);await sheets(env,`/values/${encodeURIComponent(`${sheet}!A:C`)}:append?valueInputOption=RAW&insertDataOption=INSERT_ROWS`,{method:'POST',body:JSON.stringify({values:[[table.id,count+1,'']]})})}
async function ensureDD(env){const meta=await sheets(env,'?fields=sheets(properties(title))');if(!(meta.sheets||[]).some(s=>s.properties.title==='DD'))await sheets(env,':batchUpdate',{method:'POST',body:JSON.stringify({requests:[{addSheet:{properties:{title:'DD'}}}]})});const range=encodeURIComponent('DD!A1:G1'),current=await sheets(env,`/values/${range}`),head=current.values?.[0]||[];if(head.join('\u001f')==='Ngày\u001fTên\u001fLớp\u001fTrạng thái\u001fBên\u001fBàn\u001fVị trí')return;await sheets(env,`/values/${range}?valueInputOption=RAW`,{method:'PUT',body:JSON.stringify({values:[['Ngày','Tên','Lớp','Trạng thái','Bên','Bàn','Vị trí']]})})}
async function ddRows(env){const result=await sheets(env,`/values/${encodeURIComponent('DD!A2:G')}`);return (result.values||[]).map((v,index)=>({sheetRow:index+2,date:String(v[0]||''),name:String(v[1]||''),className:String(v[2]||''),status:String(v[3]||''),side:String(v[4]||''),table:String(v[5]||''),position:Number(v[6])})).filter(x=>x.date&&x.name)}
async function reportAttendance(env,b){const date=String(b.date||''),seats=Array.isArray(b.seats)?b.seats:[];if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new Error('Ngày điểm danh không hợp lệ');await ensureDD(env);const existing=await ddRows(env),seen=new Set(),updates=[],append=[];for(const s of seats){const name=String(s.name||'').trim(),className=String(s.className||'').trim(),side=s.side==='female'?'female':'male',table=String(s.row||''),position=Number(s.position);if(!name||!parseTable(table)||!Number.isInteger(position))continue;const key=`${date}\u001f${name}\u001f${className}`;if(seen.has(key))continue;seen.add(key);const values=[date,name,className,s.absent?'Vắng':'Có mặt',side,table,position],found=existing.find(x=>x.date===date&&x.name===name&&x.className===className);if(found)updates.push({range:`DD!A${found.sheetRow}:G${found.sheetRow}`,values:[values]});else append.push(values)}if(updates.length)await sheets(env,'/values:batchUpdate',{method:'POST',body:JSON.stringify({valueInputOption:'RAW',data:updates})});if(append.length)await sheets(env,`/values/${encodeURIComponent('DD!A:G')}:append?valueInputOption=RAW&insertDataOption=INSERT_ROWS`,{method:'POST',body:JSON.stringify({values:append})});return {date,reported:seen.size,absent:seats.filter(s=>s.absent&&s.name).length}}
async function attendance(env,date){await ensureDD(env);const rows=await ddRows(env),counts=new Map();for(const row of rows)if(row.status==='Vắng'){const key=`${row.name}\u001f${row.className}`;counts.set(key,(counts.get(key)||0)+1)}return rows.filter(x=>x.date===date&&x.status==='Vắng').map(x=>({...x,count:counts.get(`${x.name}\u001f${x.className}`)||0}))}

export class SeatRoom {constructor(ctx){this.ctx=ctx}async fetch(request){if(request.headers.get('Upgrade')!=='websocket')return new Response('WebSocket required',{status:426});const [client,server]=Object.values(new WebSocketPair());this.ctx.acceptWebSocket(server);return new Response(null,{status:101,webSocket:client})}webSocketMessage(ws,message){if(typeof message!=='string')return;for(const socket of this.ctx.getWebSockets())if(socket.readyState===WebSocket.OPEN&&socket!==ws)socket.send(message)}}
export default {async fetch(request,env){if(request.method==='OPTIONS')return new Response(null,{headers:cors(request,env)});try{const u=new URL(request.url);if(u.pathname==='/api/live'){const origin=request.headers.get('Origin');if(env.ALLOWED_ORIGIN&&origin&&origin!==env.ALLOWED_ORIGIN)return new Response('Forbidden',{status:403});return env.SEAT_ROOM.getByName(SPREADSHEET_ID).fetch(request)}if(u.pathname==='/api/plan'&&request.method==='GET')return json(await plan(env),request,env);if(u.pathname==='/api/seat'&&request.method==='POST')return json({ok:true,cell:await updateSeat(env,await request.json())},request,env);if(u.pathname==='/api/seat/add'&&request.method==='POST'){await addSeat(env,await request.json());return json({ok:true},request,env)}if(u.pathname==='/api/attendance'&&request.method==='GET')return json(await attendance(env,u.searchParams.get('date')||''),request,env);if(u.pathname==='/api/attendance'&&request.method==='POST')return json(await reportAttendance(env,await request.json()),request,env);return json({error:'Not found'},request,env,404)}catch(e){return json({error:e.message||'Server error'},request,env,500)}}};
